### ISSUE TITLE
Extension support on Forge

### ISSUE THREAD

**Issue by paullakra** [light-and-ray/sd-webui-cn-in-extras-tab#3]
The error says the following while installing.

`*** Extension "sd-webui-cn-in-extras-tab" requires "sd-webui-controlnet" which is not installed.
Installing None
*** Extension "sd-webui-cn-in-extras-tab" requires "sd-webui-controlnet" which is not installed.`

The error after starting the server.

`2024-02-26 20:17:58,014 - ControlNet - INFO - ControlNet UI callback registered.
*** Cannot init ControlNet Preprocessor
    Traceback (most recent call last):
      File "D:\Projects\stable-diffusion-webui-forge\extensions\sd-webui-cn-in-extras-tab\scripts\cn_in_extras_tab.py", line 80, in ui
        self.default_unit = get_default_ui_unit()
      File "D:\Projects\stable-diffusion-webui-forge\extensions\sd-webui-cn-in-extras-tab\scripts\cn_in_extras_tab.py", line 65, in get_default_ui_unit
        from scripts.controlnet_ui.controlnet_ui_group import UiControlNetUnit
    ModuleNotFoundError: No module named 'scripts.controlnet_ui'

---
Running on local URL:  http://127.0.0.1:7860/ `

This likely happened because Forge has its controlnet extension inbuilt, which is different compared to the regular extension in naming.

**Comment by light-and-ray** [comment]
https://github.com/light-and-ray/sd-webui-cn-in-extras-tab/issues/2
